# Generated by Django 5.2.5 on 2025-11-02 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal_venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'canal_venta',
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Formas_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'formas_pago',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ramos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Tipo_DNI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Tipo_DNI',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Poliza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('valor', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'tipo_poliza',
            },
        ),
        migrations.CreateModel(
            name='TipoInteraccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_interaccion',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.ciudades')),
                ('id_tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.tipo_dni')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.departamentos'),
        ),
        migrations.CreateModel(
            name='Polizas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clientes')),
                ('id_canal_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.canal_venta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.productos')),
                ('id_tipo_poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.tipo_poliza')),
            ],
            options={
                'db_table': 'polizas',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='id_ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.ramos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='CRM.empresa')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.roles')),
                ('tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.tipo_dni')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reclamaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clientes')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, related_name='reclamacion_estado', to='CRM.estado')),
                ('poliza', models.ForeignKey(db_column='id_poliza', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.polizas')),
                ('dni_asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.usuarios')),
            ],
            options={
                'db_table': 'reclamaciones',
            },
        ),
        migrations.CreateModel(
            name='Interacciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clientes')),
                ('id_tipo_interaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.tipointeraccion')),
                ('dni_asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.usuarios')),
            ],
            options={
                'db_table': 'interacciones',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_admin', to='CRM.usuarios'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='CRM.usuarios'),
        ),
    ]
