# Generated by Django 5.2.5 on 2025-11-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizas',
            name='id_forma_pago',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.formas_pago'),
            preserve_default=False,
        ),
    ]
