# Generated by Django 5.2.5 on 2025-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_polizas_id_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='asunto',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
