# Generated by Django 5.2.5 on 2025-11-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_interacciones_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamaciones',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
