# Generated by Django 6.0 on 2025-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_reclamaciones_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
