# Generated by Django 6.0 on 2025-12-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
    ]
