# Generated by Django 6.0 on 2025-12-03 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_remove_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='interacciones',
            name='dni_asesor',
        ),
        migrations.RemoveField(
            model_name='interacciones',
            name='dni_cliente',
        ),
        migrations.RemoveField(
            model_name='interacciones',
            name='id_tipo_interaccion',
        ),
        migrations.RemoveField(
            model_name='reclamaciones',
            name='dni_asesor',
        ),
        migrations.RemoveField(
            model_name='reclamaciones',
            name='dni_cliente',
        ),
        migrations.RemoveField(
            model_name='reclamaciones',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='reclamaciones',
            name='poliza',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo_dni',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='polizas',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='polizas',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='polizas',
            name='id_estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CRM.estado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Interacciones',
        ),
        migrations.DeleteModel(
            name='Reclamaciones',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
