# Generated by Django 6.0 on 2025-12-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_remove_usuarios_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizas',
            name='id_forma_pago',
        ),
    ]
