# Generated by Django 6.0 on 2025-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_remove_polizas_id_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_poliza',
            name='valor',
        ),
        migrations.AlterField(
            model_name='polizas',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
