# Generated by Django 6.0 on 2025-12-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_remove_tipo_poliza_valor_alter_polizas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_cuenta',
            },
        ),
        migrations.RemoveField(
            model_name='ciudades',
            name='id_departamento',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.tipo_cuenta'),
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
    ]
