# Generated by Django 6.0 on 2025-12-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_tipo_cuenta_remove_ciudades_id_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id_ramo',
        ),
        migrations.DeleteModel(
            name='Ramos',
        ),
    ]
